### ISSUE TITLE
Uninstall Zotify Completely

### ISSUE THREAD

**Issue by EY003** [zotify-dev/zotify#105]
How to uninstall Zotify and the tools and software required to install along with it completely from Windows? I searched in the documents provided and didn't find a way, also using {zotify --help} inside the PowerShell doesn't help, can you help me if you happened to know a way, please.

![trash-can-icon-28](https://github.com/zotify-dev/zotify/assets/165222058/b708404d-318e-438c-a55f-f5f7ef18fc9d)

**Comment by ArjixWasTaken** [comment]
If all you did when installing is:

> python -m pip install git+https://zotify.xyz/zotify/zotify.git

you can run

> python -m pip uninstall git+https://zotify.xyz/zotify/zotify.git

to uninstall it
