### ISSUE TITLE
lyrics are not getting fetched (for all songs, even ones that actually have lyrics on spotify)

### ISSUE THREAD

**Issue by iop0p** [zotify-dev/zotify#120]
Spotify API Error (unknown): received an empty response
###   Skipping lyrics for /song name/   ###

**Comment by AdamRopelewski** [comment]
Very easy and actually working fix. Thanks

**Comment by iop0p** [comment]
can confirm it works
thanks @FlyingButteryTuna

**Comment by snehilshah** [comment]
So can I edit this in my existing installation?

Edit:
So in my installation with pipx on ubuntu was on path: `/home/<username>/.local/share/pipx/venvs/zotify/lib/python3.12/site-packages/zotify`, check where your installation method installs zotify
