### ISSUE TITLE
Lyrics of Russian songs will not download even though they are in Spotify.

### ISSUE THREAD

**Issue by fartfartfarty** [zotify-dev/zotify#13]
Command prompt outputs:  Skipping lyrics for УННВ - Убиты но не вами: lyrics not available

The [song](https://open.spotify.com/track/1rZmtfMalUzjhYtgpawBjq?si=9dbd5a9c790b416f) has lyrics when you click on it on Spotify. I tested and it worked on songs with English lyrics. Each song does have a .lrc file with it but it only shows the time of the first lyric.

**Comment by zotify-dev** [comment]
I believe this is related to https://github.com/zotify-dev/zotify/commit/8cfd27407e8bacc50d43c8983a97443b29a2b7cf. Please ensure you have the latest version of Zotify installed.
If this is still occurring on the latest version please supply your OS and system locale.

**Comment by fartfartfarty** [comment]
All working fine now. Thanks.
