### ISSUE TITLE
.song_ids format?

### ISSUE THREAD

**Issue by Suncatcher** [zotify-dev/zotify#16]
When I make download of the playlsit, in the output folder I always find the **.song_ids** file with mysterious numbers in the first column
```
7fd3ufuESeBC8kyqo7Lzbs	2023-08-14 09:07:44	Proyal	1001 Nights - Original Mix	Proyal - 1001 Nights - Original Mix.mp3
1VpoazEusm1ki8hoSK49ua	2023-08-14 09:07:55	Paolo Pellegrino	'74 - '75 (feat. Susan Tyler) - Radio Edit	Paolo Pellegrino - '74 - '75 (feat. Susan Tyler) - Radio Edit.mp3
3leKR9bTU8RGm1VnwJV1CS	2023-08-14 09:08:20	Menno de Jong	Abhyasa	Menno de Jong - Abhyasa.mp3
3VWh4Gs34HeTBUvv9bnLQL	2023-08-14 09:08:31	BiXX	Above The Clouds	BiXX - Above The Clouds.mp3
```
This doesn't correspond to the ID of the song when I copy its link via Spotify app, not Youtube IDs.
Where the come from?

**Comment by zotify-dev** [comment]
The IDs are Spotify track IDs.
Examples:
https://open.spotify.com/track/7fd3ufuESeBC8kyqo7Lzbs
https://open.spotify.com/track/1VpoazEusm1ki8hoSK49ua
https://open.spotify.com/track/3leKR9bTU8RGm1VnwJV1CS
https://open.spotify.com/track/3VWh4Gs34HeTBUvv9bnLQL

**Comment by Suncatcher** [comment]
oh, you are right, I was checking through the last segment of track URL open.spotify.com/track/7fd3ufuESeBC8kyqo7Lzbs?si=**a0352c14e33049ed**, but the ID resides in the beginning. Thanks.
