### ISSUE TITLE
BadCredentials

### ISSUE THREAD

**Issue by ghost** [zotify-dev/zotify#191]
I'm using ubuntu. I used the workaround to get the credentials.json file, but it still asks for login and gets the BadCredentials error. Any solutions?

**Comment by j1gg3** [comment]
your config.json needs to point to credentials.json otherwise it won't work.

**Comment by ghost** [comment]
How does it need to be formatted? Currently it doesn't work and its "CREDENTIALS_LOCATION": "./home/USERNAME/Downloads/librespot-auth-x86_64-linux-musl-static/credentials.json"

**Comment by ghost** [comment]
Solved, made a typo in credentials.json

**Comment by caoilainnl** [comment]
How to get the credentials on Mac https://github.com/zotify-dev/zotify/issues/181#issuecomment-2428102939 (It might work for any OS actually)

Using the Oauth method
