### ISSUE TITLE
[Errno 13] but with permission to folder...

### ISSUE THREAD

**Issue by Philipzoid** [zotify-dev/zotify#213]
I get the following error message when trying to download songs. i checked my permissions, ran in administrator mode and checked if i could add something to the playlist which i could. i also changed the folder to my downloads folder and this also did not solve it.

[Errno 13] Permission denied: 'C:\\Users\\my name\\Spotifydl'

Traceback (most recent call last):
  File "C:\Users\my name\pipx\venvs\zotify\Lib\site-packages\zotify\track.py", line 186, in download_track
    check_all_time = scraped_song_id in get_previously_downloaded()
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\my name\pipx\venvs\zotify\Lib\site-packages\zotify\utils.py", line 42, in get_previously_downloaded
    with open(archive_path, 'r', encoding='utf-8') as f:
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\my name\\Spotifydl'

**Comment by Philipzoid** [comment]
solved! the issue was with my config.json

**Comment by tehdamusic** [comment]
what was the fix

**Comment by Philipzoid** [comment]
I needed to add // instead of / in my directory
