### ISSUE TITLE
> I can confirm, Zotify works fine after generating credentials.json. **So this is the complete guide:**

### ISSUE THREAD

**Issue by PromfKwink** [zotify-dev/zotify#223]
> I can confirm, Zotify works fine after generating credentials.json. **So this is the complete guide:**
> 
> 1. Download Rust "Assuming you're on Windows: Install Rust from https://www.rust-lang.org/tools/install"
> 2. Open **new** Windows Powershell and type: git clone https://github.com/dspearson/librespot-auth.git
> 3. Open ...\librespot-auth\src\main.py and change 'Speaker' to 'Computer' in two places like this:
>    ![image](https://private-user-images.githubusercontent.com/3504928/386960195-55dbdf07-3ed9-4a27-b3ad-7d02db0a9383.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1OTM3MTAsIm5iZiI6MTczMzU5MzQxMCwicGF0aCI6Ii8zNTA0OTI4LzM4Njk2MDE5NS01NWRiZGYwNy0zZWQ5LTRhMjctYjNhZC03ZDAyZGIwYTkzODMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDdUMTc0MzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmFiZjc1NzBiOTVjMzc0Y2U5MWE1Nzc4YTZkMDVlMzg2MmFlNDcxNWRlMTZmYWZkMWNjZjhjZjYxZjA4ZWY2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.o90uErO6W8_xj6gWbZs1Bj7L5bizfRiLmS5UL78pbzU)
>    Save it
> 
> 4)cd librespot-auth cargo build --release Now You should have a librespot-auth.exe file in the librespot-auth/target/debug/ folder. Run it inside the powershell.
> 
> > it tells you "_Open Spotify and select output device: Speaker_", this is what you do next :
> > 
> > * run the spotify app (the credentials operation won't work from Spotify webpage),
> > * log the Spotify app in to your account (non premium account is ok :) ),
> > * click the "Connect a device" button (Spot app screen bottom right, at the left of volume bar),
> > * select device "Speaker" in the list and ...
> >   ... voilà ! -> the modded librespot-auth exe exits having generated the credentials.json file in its subdir.
> 
> 5. Modify the credentials.json as follows:
>    Replace "auth_type": 1 with "type":"AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS"
>    Rename "auth_data" to "credentials"
> 6. Open C:\Users\your_user\AppData\Roaming\Zotify\config.json
>    at least specify path to the credential.json. I also specified temp folders(make sure you created it first):
>    ![image](https://private-user-images.githubusercontent.com/3504928/386961630-445457db-a8de-4a7c-937f-ff3939f74236.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1OTM3MTAsIm5iZiI6MTczMzU5MzQxMCwicGF0aCI6Ii8zNTA0OTI4LzM4Njk2MTYzMC00NDU0NTdkYi1hOGRlLTRhN2MtOTM3Zi1mZjM5MzlmNzQyMzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDdUMTc0MzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDhkZWQyMzEzZDk1ZjlhMjk2ODRkYjFjZTgwNTFiOTkxYWY0NjZhZDJlNjZmNGI0MGFjOWU3OTQ3MjU3NzNlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.OBOd3MWUCx38AcwgmE9a8QPuxHLyzpKhkOP8Q8CbOCA)
> 7. DONE! Now you should be able to run 'zotify <url to track/playlist/etc>'
>    Find downloaded tracks in C:\Users\your_user\Music\Zotify Music
> 
> Please thumb up if this helps. And have an amazing day enjoying your favorite tracks! ;)

Hey, I would love to use this but I get stuck on step 4.  Powershell gives me the following error when I try to run it:
![image](https://github.com/user-attachments/assets/526b54d6-fb53-4cd7-beaa-99c1ab07fbe1)
How could I solve this? I do not have much experience coding or anything but I already appreciate you helping people here :)

_Originally posted by @PromfKwink in https://github.com/zotify-dev/zotify/issues/174#issuecomment-2525259025_

It also doesn't work if I replace 'cargo' with '.cargo' by the way, as this is how my librespot-auth looks like: 
![image](https://user-images.githubusercontent.com/190962659/393538492-58498def-798d-40b6-a812-9d5bf065191f.png)

**Comment by cgrylmz** [comment]
I got this message: "thread 'main' panicked at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library\core\src\ops\function.rs:250:5:
called `Result::unwrap()` on an `Err` value: Error { kind: InvalidArgument, error: HmacError([]) }" when i open Spotify and Connect to computer.

**Comment by sallyjuettner** [comment]
> I got this message: "thread 'main' panicked at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library\core\src\ops\function.rs:250:5: called `Result::unwrap()` on an `Err` value: Error { kind: InvalidArgument, error: HmacError([]) }" when i open Spotify and Connect to computer.

I had exactly the same problem. Did you ever find a solution?

**Comment by 4LEXS1S** [comment]
Did it ever get fixed. Im new to this and this is the only solution that i found to my problem? does it work?
