### ISSUE TITLE
Spotify API Error (unknown): received an empty response

### ISSUE THREAD

**Issue by rahaaatul** [zotify-dev/zotify#5]
###   Skipping lyrics for ATSMXN - Disco Phonk: lyrics not available   ###

**Comment by zotify-dev** [comment]
Not a bug, it's just letting you know there aren't any lyrics to download for that track. The program will still run as expected.
If you don't care about lyrics and just want the warning message to go away, turn off `DOWNLOAD_LYRICS` in the config or add `--download-lyrics=False` to your command.
