### ISSUE TITLE
Download location of music not changing

### ISSUE THREAD

**Issue by aihcnas** [zotify-dev/zotify#63]
Hi, what is the correct way of changing the music output directory of the downloaded music folder? I wish to save them in my SSD drive instead of the default Zotify Music folder.

I've tried the following methods which didn't work for me:

1. Editing the .config file and inserting the desired output address within:
"ROOT_PATH": "D:\User\Users Music\Custom Zotify Music Folder",

2. Using this command within the powershell:
  zotify --root-path D:\User\Users Music\Custom Zotify Music Folder
  
  
 Please let me know if I'm missing something. TIA!

**Comment by timkgh** [comment]
Try changing to forward slashes or double backslashes:
`D:/User/Users Music/Custom Zotify Music Folder`
`D:\\User\\Users Music\\Custom Zotify Music Folder`

**Comment by aihcnas** [comment]
Got it working after a lot of trials. 
Apparently, inserting `--root-path` at the very beginning of the command was the culprit. 

Inserting it at the end of the command worked:
`zotify --download-format mp3 --download-quality very_high --root-path D:\User\Users Music\Custom Zotify Music Folder https://open.spotify.com/track/`

Thanks for your input! Using forward slashes or double backslashes also works.
