### ISSUE TITLE
[Feature request] Download album art

### ISSUE THREAD

**Issue by Kuroonehalf** [zotify-dev/zotify#77]
Like the title says, it'd be nice if Zotify could download the album's cover. Being able to set its file name in the settings would be great too.

**Comment by shinji257** [comment]
Last I checked it does already as part of the metadata.  The cover gets embedded in the audio file.

**Comment by Kuroonehalf** [comment]
I'd like it as its own file, so I could use it to display as the folder thumbnail.

**Comment by zotify-dev** [comment]
Probably won't add that in, but here is a command to extract cover art with FFmpeg: `ffmpeg -i <song>.ogg -an -vcodec copy cover.jpg`
